// This code is to be copy pasted in you vivtis application component
// alongside data generated by the python generator
// 

#include "xparameters.h"
#include "xaxidma.h"
#include <stdio.h>
#include <xstatus.h>
#include "mnist_samples.h"

XAxiDma AxiDma;

int init_dma(XAxiDma *AxiDma) {
    XAxiDma_Config* CfgPtr;
    int status;

    CfgPtr = XAxiDma_LookupConfig(XPAR_AXI_DMA_0_BASEADDR);
    if (!CfgPtr) {
        xil_printf("No configuration found for %d\n", XPAR_AXI_DMA_0_BASEADDR);
        return XST_FAILURE;
    }

    status = XAxiDma_CfgInitialize(AxiDma, CfgPtr);
    if (status != XST_SUCCESS) {
        xil_printf("Initialization failed\n");
        return XST_FAILURE;
    }

    if (XAxiDma_HasSg(AxiDma)) {
        xil_printf("Device configured as SG mode\n");
        return XST_FAILURE;
    }

    return XST_SUCCESS;
}

int main(void) {
    int status = init_dma(&AxiDma);
    if(status != XST_SUCCESS) {
        xil_printf("Error while initializing the DMA\n");
        return 1;
    }

    xil_printf("DMA initialized successfully\n");

    volatile char TxBuffer[IMAGE_SIZE*NUM_SAMPLES] __attribute__ ((aligned (32)));
    volatile int RxBuffer[NUM_SAMPLES] __attribute__ ((aligned (32)));

    for(int j = 0; j < NUM_SAMPLES; j++) {
        for(int i = 0; i < IMAGE_SIZE; i++) {
            TxBuffer[j * IMAGE_SIZE + i] = (char)mnist_samples[j][i]; // fill with variable placeholder data
        }
    }

    Xil_DCacheFlushRange((UINTPTR)TxBuffer, NUM_SAMPLES * IMAGE_SIZE * sizeof(char));
    Xil_DCacheFlushRange((UINTPTR)RxBuffer, NUM_SAMPLES * sizeof(char));

    for(int k = 0; k < NUM_SAMPLES; k++) {

        status = XAxiDma_SimpleTransfer(&AxiDma, (UINTPTR)&TxBuffer[k*IMAGE_SIZE], IMAGE_SIZE * sizeof(char), XAXIDMA_DMA_TO_DEVICE);
        //printf("%i TO_DEVICE status code\n", status);
        if (status != XST_SUCCESS) {
            xil_printf("Error: DMA transfer to device failed\n");
            return XST_FAILURE;
        }

        status = XAxiDma_SimpleTransfer(&AxiDma, (UINTPTR)&RxBuffer[k], sizeof(int), XAXIDMA_DEVICE_TO_DMA);
        //printf("%i FROM_DEVICE status code\n", status);
        if (status != XST_SUCCESS) {
            xil_printf("Error: DMA transfer from device failed\n");
            return XST_FAILURE;
        }

        while (XAxiDma_Busy(&AxiDma, XAXIDMA_DMA_TO_DEVICE) || 
               XAxiDma_Busy(&AxiDma, XAXIDMA_DEVICE_TO_DMA)) {
            ;
        }
        xil_printf("#%i iteration done\n", k);
    }


    for(int i = 0; i < NUM_SAMPLES; i++) {
        xil_printf("FPGA value RxBuffer[%d] = %d\n", i, RxBuffer[i]);
    }

    return 0;
}